"use client";

import { CheckCircle2, Sparkles, Wand2 } from "lucide-react";

import type { CampaignStepProps } from "@/types/campaign";

const GENERATED_CREATIVE_URL = "https://app.cpcadvertising.com/brand/cpcadvertising-logo.png";

const cleanProductName = (value: string) =>
  value
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0]
    .replace(/\.[a-z]{2,}$/i, "")
    .replace(/[-_]/g, " ")
    .trim();

const buildCreativeOptions = (draft: CampaignStepProps["draft"]) => {
  const product = draft.productName || cleanProductName(draft.displayUrl || draft.landingPageUrl) || "your product";
  const cpc = draft.bidAmount || "0.25";
  const restrictionHint = draft.restrictions ? "Built with your restrictions applied." : "Ready to test across paid click channels.";
  const audience = draft.targetCustomer || "qualified buyers";
  const benefit = draft.keyBenefit || "a faster way to get what they need";
  const cta = draft.callToAction || "See the product";

  return [
    {
      title: `${cta}: ${product}`,
      message: `${benefit} for ${audience}. CPCAdvertising.com tunes this around a max CPC of $${cpc}.`,
      angle: "Direct response"
    },
    {
      title: `Is ${product} right for you?`,
      message: `${draft.offerAngle || "A product-led click campaign"} with creative shaped around ${draft.brandTone || "a clear performance tone"}.`,
      angle: "Consideration"
    },
    {
      title: `Looking for ${product}? Start here`,
      message: `${draft.visualDirection || "Clean product creative"} routed to ${draft.displayUrl || "the product page"}. ${restrictionHint}`,
      angle: "Search intent"
    }
  ];
};

export function CreativeStep({ draft, updateDraft }: CampaignStepProps) {
  const options = buildCreativeOptions(draft);

  const selectCreative = (creative: { title: string; message: string }) => {
    updateDraft({
      creativeUrl: draft.extractedProduct.imageUrl || draft.creativeUrl || GENERATED_CREATIVE_URL,
      headline: creative.title,
      description: creative.message
    });
  };

  return (
    <div className="grid gap-5">
      <section className="rounded-lg border border-emerald-200 bg-emerald-50 p-4">
        <div className="flex items-start gap-3">
          <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white text-brand-green">
            <Sparkles className="h-5 w-5" />
          </span>
          <div>
            <p className="text-xs font-extrabold uppercase text-brand-green">Generated by CPCAdvertising.com</p>
            <h3 className="mt-1 text-lg font-extrabold">Creative set ready</h3>
            <p className="mt-2 text-sm leading-6 text-muted">
              We use the product URL, extracted product details, and the design brief below to shape the ad concepts.
              A customer can bring a creative URL as source material without having to build the final ads themselves.
            </p>
          </div>
        </div>
      </section>

      <section className="rounded-lg border border-line bg-white p-4">
        <p className="text-xs font-extrabold uppercase text-brand-green">Creative design brief</p>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <BriefField
            label="Who should click?"
            value={draft.targetCustomer}
            onChange={(value) => updateDraft({ targetCustomer: value })}
          />
          <BriefField
            label="Main benefit"
            value={draft.keyBenefit}
            onChange={(value) => updateDraft({ keyBenefit: value })}
          />
          <BriefField
            label="Brand tone"
            value={draft.brandTone}
            onChange={(value) => updateDraft({ brandTone: value })}
          />
          <BriefField
            label="Offer angle"
            value={draft.offerAngle}
            onChange={(value) => updateDraft({ offerAngle: value })}
          />
        </div>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <BriefField
            label="Visual direction"
            textarea
            value={draft.visualDirection}
            onChange={(value) => updateDraft({ visualDirection: value })}
          />
          <BriefField
            label="Call to action"
            textarea
            value={draft.callToAction}
            onChange={(value) => updateDraft({ callToAction: value })}
          />
        </div>
      </section>

      <div className="grid gap-3">
        {options.map((creative) => {
          const selected = draft.headline === creative.title && draft.description === creative.message;
          return (
            <button
              key={creative.title}
              className={[
                "rounded-lg border p-4 text-left transition",
                selected ? "border-brand-blue bg-[#eef6ff]" : "border-line bg-white hover:border-brand-blue/30"
              ].join(" ")}
              type="button"
              onClick={() => selectCreative(creative)}
            >
              <span className="flex items-center justify-between gap-3">
                <span className="text-xs font-extrabold uppercase text-brand-green">{creative.angle}</span>
                {selected ? <CheckCircle2 className="h-5 w-5 text-brand-blue" /> : null}
              </span>
              <strong className="mt-2 block text-lg leading-tight">{creative.title}</strong>
              <span className="mt-2 block text-sm leading-6 text-muted">{creative.message}</span>
            </button>
          );
        })}
      </div>

      <section className="rounded-lg border border-line bg-white p-4">
        <div className="flex items-center gap-2">
          <Wand2 className="h-5 w-5 text-brand-blue" />
          <p className="text-xs font-extrabold uppercase text-brand-green">Ad preview</p>
        </div>
        {draft.extractedProduct.imageUrl ? (
          <div className="mt-3 overflow-hidden rounded-lg border border-line bg-slate-50">
            <img
              alt={draft.productName || "Imported product creative"}
              className="h-44 w-full object-cover"
              src={draft.extractedProduct.imageUrl}
            />
          </div>
        ) : null}
        <div className="mt-3 rounded-lg bg-[#101816] p-4 text-white">
          <span className="text-xs font-extrabold uppercase text-emerald-200">Sponsored</span>
          <h3 className="mt-2 text-xl font-extrabold leading-tight">{draft.headline}</h3>
          <p className="mt-2 leading-6 text-white/75">{draft.description}</p>
          <span className="mt-3 block font-extrabold text-emerald-200">
            {draft.displayUrl || "product-url.com"}
          </span>
        </div>
      </section>

      <section className="rounded-lg border border-line bg-slate-50 p-4">
        <p className="text-xs font-extrabold uppercase text-muted">Approval mode</p>
        <p className="mt-2 text-sm leading-6 text-ink">
          {draft.customerApprovalMode === "review_first"
            ? "Customer approval is required before CPCAdvertising.com submits the ads to partner platforms."
            : "CPCAdvertising.com can submit the generated ads directly to partner platforms and optimize for clicks."}
        </p>
      </section>
    </div>
  );
}

function BriefField({
  label,
  onChange,
  textarea = false,
  value
}: {
  label: string;
  onChange: (value: string) => void;
  textarea?: boolean;
  value: string;
}) {
  const className =
    "rounded-lg border border-line bg-white px-3 py-3 outline-none focus:border-brand-green focus:ring-4 focus:ring-emerald-100";

  return (
    <label className="grid gap-2">
      <span className="text-sm font-extrabold uppercase text-muted">{label}</span>
      {textarea ? (
        <textarea className={`${className} min-h-24`} value={value} onChange={(event) => onChange(event.target.value)} />
      ) : (
        <input className={`${className} min-h-11`} value={value} onChange={(event) => onChange(event.target.value)} />
      )}
    </label>
  );
}
